project_id = "lgffdjrwblfycfqarstj"

[functions.daily-migration]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.update-user-profile]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.logout-all-devices]
verify_jwt = false