project_id = "lgffdjrwblfycfqarstj"

[functions.daily-migration]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.update-user-profile]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.logout-all-devices]
verify_jwt = false

[functions.bulk-results-upload]
verify_jwt = false

[functions.scrape-website]
verify_jwt = false

[functions.auto-sync-results]
verify_jwt = false